### ISSUE TITLE
Add compatibility for fenix 8 47mm

### ISSUE THREAD

**Issue by Lysuo** [pedrorijo91/garmin-padel#104]
Hi
could you add the compatibility for fenix 8 47mm ?
I can only see the 43mm listed in the compatible devices on the Connect IQ `application's page, although I guess it should work pretty much the same on both models.
Cheers

**Comment by pedrorijo91** [comment]
hey @Lysuo . when fenix 8 came out i added support right away. at the time there was only 1 fenix8 device in the developer SDK, the 43mm. and it worked. now there were some updates, and all fenix8 devices require us to increase the minApiLevel (currently `2.4.0,` requires at least `5.0.1`). need to check which devices would stop being supported

**Comment by pedrorijo91** [comment]
looking here, it seems quite a few could become unsupported https://developer.garmin.com/connect-iq/compatible-devices/, like a lot of the forerunner devices, and even fenix 6


<img width="1168" alt="image" src="https://github.com/user-attachments/assets/417b2fa0-3bda-4836-9e85-975acda36b03">

**Comment by pedrorijo91** [comment]
looking for alternatives in forum https://forums.garmin.com/developer/connect-iq/f/discussion/397836/how-to-make-a-watch-app-for-forerunner-245-and-fenix-8

**Comment by Lysuo** [comment]
Thanks for your quick response & investigation on this
I don't know much about the garmin SDK.. isn't there some sort of backward-compatiblity so that older devices are not left behind when new ones show up on the market ?

**Comment by pedrorijo91** [comment]
seems like there was a bug on the SDK which was fixed already :) will push support for fenix8 today/this weekend and release next

**Comment by Lysuo** [comment]
Great! Thanks :)

**Comment by pedrorijo91** [comment]
just released v1.13.0 with support for fenix 8. should become available in the next few minutes @Lysuo

**Comment by Lysuo** [comment]
Awesome thanks! I've downloaded it, works well on my watch, will test it in a real game next week :)
