### ISSUE TITLE
heart rate icon is overlapping with the heart rate value

### ISSUE THREAD

**Issue by pedrorijo91** [pedrorijo91/garmin-padel#67]
according with @Jorman, `the heart rate icon is overlapping with the heart rate value`

Device Name: Fenix 7x Solar Sapphire

**Comment by Jorman** [comment]
Ciao Pedro,
yes, thank you.
Do you need one screen to see what happen?

**Comment by pedrorijo91** [comment]
i can probably reproduce it on the emulator, but an image would help surely :)

**Comment by Jorman** [comment]
Sure, here a photo
![1695895274380](https://github.com/pedrorijo91/garmin-padel/assets/5203988/9d480b67-7712-4699-af2b-81706d1f5a44)
J

**Comment by pedrorijo91** [comment]
to be released soon under version 1.6.1

**Comment by pedrorijo91** [comment]
released. should be available very soon in garmin app store for update

**Comment by Jorman** [comment]
Ok, thanks!
I will tell you something about how it works, because it was doing it even with less than 10k steps.
I'll keep you updated either way!

J

**Comment by Jorman** [comment]
1.6.1 installed and working like a charm, even with less than 10k steps.

Thanks

**Comment by pedrorijo91** [comment]
seems to be still happening in fenix 7, as reported in video https://github.com/pedrorijo91/garmin-padel/issues/72

**Comment by Jorman** [comment]
Maybe the problem is in the whole Fenix 7 family
