### ISSUE TITLE
Unable to exit application after start

### ISSUE THREAD

**Issue by Jorman** [pedrorijo91/garmin-padel#68]
Hi,
I don't know whether it's a bug, whether it's intended or whether it's a limitation of the clock, but if I open the application, the back button doesn't work and I can't exit the application, I've to start the game and then exit.
My device is Fenix 7x Solar Sapphire

Let me know

**Comment by pedrorijo91** [comment]
Hey @Jorman 

yes, i did not implement a "quick exit" from the menu. yet.....

**Comment by Jorman** [comment]
Ok, no problem, just to know.
Thank you
