### ISSUE TITLE
support for FR965

### ISSUE THREAD

**Issue by svenneberka** [pedrorijo91/garmin-padel#71]
Hi,

This app looks promising :) Do you plan on adding support for Forerunner 965 with touch-screen?

Best regards,
Svante

**Comment by pedrorijo91** [comment]
hey @svenneberka ! thanks for the kind words. I've been trying to find time in supporting touch-screen devices (as firstly reported in #56), but it requires a bit more work, and summer has been a bit busy :) but since garmin started to make a bigger bet in touch-screen on lastest forerunners, i may need to find some time to work on it

**Comment by pedrorijo91** [comment]
started to look into this: app as it is, works fine in FR965, by making use of buttons to increase score

need to update screen :D

<img width="668" alt="image" src="https://github.com/pedrorijo91/garmin-padel/assets/1999050/20d378c7-e5ae-43bc-a73b-ca4006e6b114">

another detail: seems like touchscreen devices can go back by sliding back, which will go back to menu options. when selecting (again) an option it tries to start another match and it crashes

**Comment by pedrorijo91** [comment]
FR 165 seems to be exactly the same thing

**Comment by pedrorijo91** [comment]
hey @svenneberka , support for FR 965 has been added :) will release a new version tomorrow likely

while the touchscreen actions are enabled for the menu screen, during the match the score can only be added by clicking the buttons. this was kinda a quick fix for now. I will probably need to have a better thought on touchscreen devices during #78

**Comment by svenneberka** [comment]
Hi Pedro,

Thank you for this! I made some changes to the code before to get it to
work on my device, but now I can get your official version :)

Not sure if you already have addressed this, but sometimes the watch starts
the padel score app by mistake and it would be nice if the "back" button
would close the app instead of having to enter all the menu options and
save the score (to garmin, and then you have to delete it). Just a feature
request, not a big deal.

Best regards,
Svante

Den lör 24 feb. 2024 kl 00:01 skrev Pedro Rijo ***@***.***>:

**Comment by pedrorijo91** [comment]
thanks @svenneberka  ! it has been raised in #68 actually. I have personally felt this once or twice as well, but since it was not a big deal, didn't focus on solving it so far :D

i think it may not be a big change, so i may try to find some time "soon"... 😅
